### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by michaelb** [michaelb/auto-ytdl#15]
how does it sound?

**Comment by meowthed** [comment]
got picked up by Windows Defender as Trojan:Win32/Woreflint.A!cl

**Comment by michaelb** [comment]
I got that one too. Did an analysis afterwards of the same .exe afterwards, and it did not find anything.... i don't know what to think, except that I definitely love windows (/s).

I don't know what may make defender pick up my exe, since I never even ask for 'sensitive' things such as prompting admin rigths, executing something other than youtube-dl, ffmpeg and a thumbnail embedder for opus files (that one does not even works properly on windows).... It can't be that the build tools are corrupted, rigth?


You can of course build auto-ytdl yourself from sources, comments in the aytdl.py file may help you. Running directly as a python script (entry point is aytld.py) is also possible

**Comment by sphr2k** [comment]
It's being detected as suspicious by [several AV engines](https://www.virustotal.com/gui/file/8df0780a94732bdcc1c4237d3f5a5d9cb70581fb26fbad0ea004f133bab8d628/detection). I'm *not* suggesting that it is in fact malicious - maybe you're using some kind of EXE packer?)

**Comment by michaelb** [comment]
> maybe you're using some kind of EXE packer?)

Only PyInstaller (installer from the repos)  (and excluding as many unneeded libraries as possible)
A comment in the aytdl.py file describes how I compiled it for windows (and linux)

I'm a bit saddened that I can't fix it (it's supposedly a known issue: https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg ) but I don't have the windows machine anymore nor enough disk space (and patience after a failed try) to try a VM to recompile it myself
